using System;
using System.Drawing;
using System.Xml.Linq;

namespace lab2
{
    public class FileOperation
    {
        public static void CreateXML(string nameFile)
        {
            XDocument xdoc = new XDocument(new XElement("Registrations",
                            // registration1
                            new XElement("Registration",
                                new XAttribute("name", "registration1"),
                                
                                new XElement("Plane",
                                    new XAttribute("name", "plane1"),          
                                    new XElement("Label", "Sorol"),
                                    new XElement("Manufacturer", 
                                        new XAttribute("name", "manufacturer1"),
                                        new XElement("Name", "Boeing"),
                                        new XElement("Location", "usa"),
                                        new XElement("Founded", new DateTime(1916, 7, 12)),
                                        new XElement("NumberOfEmployees", 12345)), 
                                    new XElement("Model", "SLS"),
                                    new XElement("Type", "Cargo"),
                                    new XElement("YearOfIssue", new DateTime(2003, 5, 12)),
                                    new XElement("VinCode", "gushu429834fhs92")),
                                
                              
                                new XElement("PlaneCondition ", PlaneCondition.Excellent),
                                
                                new XElement("ActualPilot", new XElement("Pilot",
                                    new XAttribute("name", "pilot1"),
                                    new XElement("Name", "Tkach"),
                                    new XElement("Surname", "Yurii"),
                                    new XElement("Patronymic", "Olexandrovich"),
                                    new XElement("DateOfBirth", new DateTime(1900, 12, 3)),
                                    new XElement("AddressRegistration", "LA"),
                                    new XElement("PilotLicense", "34gsg342vxd"))),
                                
                                new XElement("AllPilots", 
                                    new XElement("Pilot",
                                        new XAttribute("name", "pilot2"),
                                        new XElement("Name", "Stephan"),
                                        new XElement("Surname", "Kupa"),
                                        new XElement("Patronymic", "Johnovich"),
                                        new XElement("DateOfBirth", new DateTime(1983, 1, 1)),
                                        new XElement("AddressRegistration", "Madrid"),
                                        new XElement("PilotLicense ", "25shh653ktc")),
                                    new XElement("Pilot",
                                        new XAttribute("name", "pilot4"),
                                        new XElement("Name", "Liubomir"),
                                        new XElement("Surname", "Vazhil"),
                                        new XElement("Patronymic", "Marmeladovich"),
                                        new XElement("DateOfBirth", new DateTime(1953, 8, 16)),
                                        new XElement("AddressRegistration", "Chortkiv"),
                                        new XElement("PilotLicense", "43kgs92xjs")))),
                            
                            // registration2
                            new XElement("Registration",
                                new XAttribute("name", "registration2"),
                                
                                new XElement("Plane",
                                    new XAttribute("name", "plane1"),
                                    new XElement("Label", "Sorol"),
                                    new XElement("Manufacturer", 
                                        new XAttribute("name", "manufacturer1"),
                                        new XElement("Name", "Boeing"),
                                        new XElement("Location", "usa"),
                                        new XElement("Founded", new DateTime(1916, 7, 12)),
                                        new XElement("NumberOfEmployees", 12345)), 
                                    new XElement("Model", "SLS"),
                                    new XElement("Type", "Cargo"),
                                    new XElement("YearOfIssue", new DateTime(2003, 5, 12)),
                                    new XElement("VinCode", "gushu429834fhs92")),
                                
                                
                                new XElement("PlaneCondition ", PlaneCondition.Good),
                                
                                new XElement("ActualPilot", new XElement("Pilot",
                                    new XAttribute("name", "pilot3"),
                                    new XElement("Name", "Lupa"),
                                    new XElement("Surname", "Pupovich"),
                                    new XElement("Patronymic", "Aethetics"),
                                    new XElement("DateOfBirth", new DateTime(1991, 6, 25),
                                    new XElement("AddressRegistration", "Berlin"),
                                    new XElement("PilotLicense", "85nrj478soi"))),
                                
                                new XElement("AllPilots", 
                                    new XElement("Pilot",
                                        new XAttribute("name", "pilot1"),
                                     new XElement("Name", "Tkach"),
                                    new XElement("Surname", "Yurii"),
                                    new XElement("Patronymic", "Olexandrovich"),
                                    new XElement("DateOfBirth", new DateTime(1900, 12, 3)),
                                    new XElement("AddressRegistration", "LA"),
                                    new XElement("PilotLicense", "34gsg342vxd")),

                                    new XElement("Pilot",
                        new XAttribute("name", "pilot4"),
                                        new XElement("Name", "Liubomir"),
                                        new XElement("Surname", "Vazhil"),
                                        new XElement("Patronymic", "Marmeladovich"),
                                        new XElement("DateOfBirth", new DateTime(1953, 8, 16)),
                                        new XElement("AddressRegistration", "Chortkiv"),
                                        new XElement("PilotLicense", "43kgs92xjs"))))),
                            
                            // registration3
                            new XElement("Registration",
                                new XAttribute("name", "registration3"),
                                
                                new XElement("Plane",
                                    new XAttribute("name", "plane2"),
                                    new XElement("Label", "Eibus"),
                                    new XElement("Manufacturer",
                                        new XAttribute("name", "manufacturer1"),
                                        new XElement("Name", "Boeing"),
                                        new XElement("Location", "usa"),
                                        new XElement("Founded", new DateTime(1916, 7, 12)),
                                        new XElement("NumberOfEmployees", 12345)),
                                    new XElement("Model", "A330-200"),
                                    new XElement("Type", "Passenger"),
                                    new XElement("YearOfIssue", new DateTime(1999, 3, 8)),
                                    new XElement("VinCode", "48tfhdg872dgjg")),
                                
                                new XElement("PlaneCondition", PlaneCondition.Good),
                                
                                new XElement("ActualPilot", new XElement("Pilot",
                                    new XAttribute("name", "pilot5"),
                                    new XElement("Name", "Gaus"),
                                    new XElement("Surname", "Mann"),
                                    new XElement("Patronymic", "Molotov"),
                                    new XElement("DateOfBirth", new DateTime(1995, 3, 3)),
                                    new XElement("AddressRegistration", "Kopengagen"),
                                    new XElement("PilotLicense", "25fhs69bfl"))),
                                
                                new XElement("AllPilots", 
                                    new XElement("Pilot",
                                        new XAttribute("name", "pilot1"),
                                    new XElement("Name", "Tkach"),
                                    new XElement("Surname", "Yurii"),
                                    new XElement("Patronymic", "Olexandrovich"),
                                    new XElement("DateOfBirth", new DateTime(1900, 12, 3)),
                                    new XElement("AddressRegistration", "LA"),
                                    new XElement("PilotLicense", "34gsg342vxd")),
                                        new XElement("Pilot",
                                        new XAttribute("name", "pilot2"),
                                        new XElement("Name", "Stephan"),
                                        new XElement("Surname", "Kupa"),
                                        new XElement("Patronymic", "Johnovich"),
                                        new XElement("DateOfBirth", new DateTime(1983, 1, 1)),
                                        new XElement("AddressRegistration", "Madrid"),
                                        new XElement("PilotLicense ", "25shh653ktc")),
                                    new XElement("Pilot",
                                    new XAttribute("name", "pilot3"),
                                    new XElement("Name", "Lupa"),
                                    new XElement("Surname", "Pupovich"),
                                    new XElement("Patronymic", "Aethetics"),
                                    new XElement("DateOfBirth", new DateTime(1991, 6, 25),
                                    new XElement("AddressRegistration", "Berlin"),
                                    new XElement("PilotLicense", "85nrj478soi"))))),

                            // registration4
                            new XElement("Registration",
                                new XAttribute("name", "registration4"),
                                
                                new XElement("Plane",
                                    new XAttribute("name", "plane3"),
                                    new XElement("Label", "Bella"),
                                    new XElement("Manufacturer", 
                                        new XAttribute("name", "manufacturer2"),
                                        new XElement("Name", "Antonov"),
                                        new XElement("Location", "UKraine"),
                                        new XElement("Founded", new DateTime(1946, 11, 21)),
                                        new XElement("NumberOfEmployee", 5432)), 
                                    new XElement("Model", "ULA"),
                                    new XElement("Type", "Passenger"),
                                    new XElement("YearOfIssue", new DateTime(1888, 1, 10)),
                                    new XElement("VinCode", "vh87dw8y3dfy2yef")),
                                  
                                new XElement("PlaneCondition", PlaneCondition.Bad),
                                
                                new XElement("ActualPilot", new XElement("Pilot",
                      new XAttribute("name", "pilot5"),
                                    new XElement("Name", "Gaus"),
                                    new XElement("Surname", "Mann"),
                                    new XElement("Patronymic", "Molotov"),
                                    new XElement("DateOfBirth", new DateTime(1995, 3, 3)),
                                    new XElement("AddressRegistration", "Kopengagen"),
                                    new XElement("PilotLicense", "25fhs69bfl"))),

                                new XElement("AllPilots", 
                                    new XElement("Pilot",
                                                         new XAttribute("name", "pilot2"),
                                        new XElement("Name", "Stephan"),
                                        new XElement("Surname", "Kupa"),
                                        new XElement("Patronymic", "Johnovich"),
                                        new XElement("DateOfBirth", new DateTime(1983, 1, 1)),
                                        new XElement("AddressRegistration", "Madrid"),
                                        new XElement("PilotLicense ", "25shh653ktc")),
                                      new XElement("Pilot",
                                        new XAttribute("name", "pilot4"),
                                        new XElement("Name", "Liubomir"),
                                        new XElement("Surname", "Vazhil"),
                                        new XElement("Patronymic", "Marmeladovich"),
                                        new XElement("DateOfBirth", new DateTime(1953, 8, 16)),
                                        new XElement("AddressRegistration", "Chortkiv"),
                                        new XElement("PilotLicense", "43kgs92xjs"))),
                                    new XElement("Pilot",
                                    new XAttribute("name", "pilot3"),
                                    new XElement("Name", "Lupa"),
                                    new XElement("Surname", "Pupovich"),
                                    new XElement("Patronymic", "Aethetics"),
                                    new XElement("DateOfBirth", new DateTime(1991, 6, 25),
                                    new XElement("AddressRegistration", "Berlin"),
                                    new XElement("PilotLicense", "85nrj478soi")))),

                            // registration5
                            new XElement("Registration",
                                new XAttribute("name", "registration5"),
                                
                                new XElement("Plane",
                                    new XAttribute("name", "plane4"),
                                    new XElement("Label", "Gondola"),
                                    new XElement("Manufacturer", 
                                        new XAttribute("name", "manufacturer3"),
                                        new XElement("Name", "Airbus"),
                                        new XElement("Location", "EU"),
                                        new XElement("Founded", new DateTime(1969, 4, 1)),
                                        new XElement("NumberOfEmployee", 7777)), 
                                    new XElement("Model", "CRJ"),
                                    new XElement("Type", "Passenger"),
                                    new XElement("YearOfIssue", new DateTime(2015, 8, 13)),
                                    new XElement("VinCode", "dghsju3y9ysdg8g")),

                                
                                new XElement("PlaneCondition", PlaneCondition.Medium),
                                
                                new XElement("ActualPilot", new XElement("Pilot",
                               new XAttribute("name", "pilot2"),
                                        new XElement("Name", "Stephan"),
                                        new XElement("Surname", "Kupa"),
                                        new XElement("Patronymic", "Johnovich"),
                                        new XElement("DateOfBirth", new DateTime(1983, 1, 1)),
                                        new XElement("AddressRegistration", "Madrid"),
                                        new XElement("PilotLicense ", "25shh653ktc"))),

                                new XElement("AllPilots",
                                               new XElement("Pilot",
                                                         new XAttribute("name", "pilot2"),
                                        new XElement("Name", "Stephan"),
                                        new XElement("Surname", "Kupa"),
                                        new XElement("Patronymic", "Johnovich"),
                                        new XElement("DateOfBirth", new DateTime(1983, 1, 1)),
                                        new XElement("AddressRegistration", "Madrid"),
                                        new XElement("PilotLicense ", "25shh653ktc")),
                          new XElement("Pilot",
                                    new XAttribute("name", "pilot5"),
                                    new XElement("Name", "Gaus"),
                                    new XElement("Surname", "Mann"),
                                    new XElement("Patronymic", "Molotov"),
                                    new XElement("DateOfBirth", new DateTime(1995, 3, 3)),
                                    new XElement("AddressRegistration", "Kopengagen"),
                                    new XElement("PilotLicense", "25fhs69bfl")),
                           new XElement("Pilot",
                                    new XAttribute("name", "pilot1"),
                                    new XElement("Name", "Tkach"),
                                    new XElement("Surname", "Yurii"),
                                    new XElement("Patronymic", "Olexandrovich"),
                                    new XElement("DateOfBirth", new DateTime(1900, 12, 3)),
                                    new XElement("AddressRegistration", "LA"),
                                    new XElement("PilotLicense", "34gsg342vxd"))))));
                        xdoc.Save(nameFile);
        }

        public static void ReadXML(string nameFile)
        {
            
        }
    }
}